### PR TITLE
 [Feature] End fishing loot tables

### PR DESCRIPTION
**Pull request by Necrontyrr**
- Non-End fishing tables are untouched.
- End loot table:
    - Fish loot table: 85%
        - End fish
    - Junk loot table: 10%. All items have the same chance.
        - Charnia. Adjusted to the biome: some have 2-4 variants, some have 0.
        - Ender pearl
        - Gelatine
        - Aurora crystal shard
        - Chorus fruit
        - End lily leaf
    - Treasure loot table: 5%. All items have the same chance.
        - Menger sponge
        - Aeternium sword blade
        - Aeternium forged plate
        - Enchanted bow (same as vanilla)
        - Enchanted end rod (same as vanilla)
        - Enchanted book (same as vanilla)

### CODE REVIEW

**Comment by ChristopherJ123** [comment]
Aeternium is a bit too good of a treasure perhaps. Not sure

**Comment by spinodal23** [comment]
I agree. Considering that ender shard and thallasium ore is burried in the end stone, and considering that aeternium requires blasting terminite with "netherite", I think that ender dust or thallasium-related things or perhaps terminite-related things would be appropriate.

**Comment by quiqueck** [comment]
Yes, I think aeternium gear should not be obtainable by fishing :)

**Comment by Necrontyrr** [comment]
I replaced aeternium with terminite and added hydralux petals.

**Comment by quiqueck** [comment]
Nice, thank you :)

**Pull request merged**
