### PR TITLE
Update `ru_ru.json`

### PR DESCRIPTION
**Pull request by mpustovoi**
Improved general consistency, reworked and added many lines.
Btw, sorry for file sorting, if anything.

### CODE REVIEW

**Comment by paulevsGitch** [comment]
You have incorrect metal names (probably some other names too). Please correct them to be the same as in original

**Comment by paulevsGitch** [comment]
Your json is also formatted differently than original, please keep same indents as in original json

**Review by paulevsGitch — CHANGES_REQUESTED** [review]
- Fix metal names
- Fix indentations

**Comment by mpustovoi** [comment]
> You have incorrect metal names (probably some other names too). Please correct them to be the same as in original

I don't understand why they are incorrect 
- `aeternium` translates as `этерний`, not `этерий`, since `этерий` is `aeterium`; one letter makes this difference
- `thallasium` should be translated as `таллазий`, not `талласий`

**Comment by paulevsGitch** [comment]
I can agree with a small typo in Aeternium name with missing letter, but Thallasium was spelled correctly and should not be changed

**Comment by mpustovoi** [comment]
Done

**Comment by paulevsGitch** [comment]
Looks like some plant names (like Jellyshrooms) were also changed, while they should not. All names should follow originals except typos and official name changes. You also reverted tabs with your latest commit. Please rebase your branch on the main header and re-implement your changes in a clean way

**Pull request closed without merging**
