### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by aoligei635**
Hey,the guy who pulled #262.You did a great job,but I'm sorry that I need to retranslate more wrong translations.And some of your translations are in my range to retranslate.If you think that translate some translations in this mod by depend the pronunciation is must to do,you can do it in your opinion.

### CODE REVIEW

**Comment by IwasConfused** [comment]
Thank you for understanding. I think each of our translations has its own advantages, and we can discuss to come up with the best translation version.

**Comment by IwasConfused** [comment]
A new translation idea:
When I looked up some previous Chinese translation documents, I found that 'thallasium' was translated as '赛蓝铁'. I think this is a translation that can be referenced. Firstly, because thallasium is a fictional substance, a word can be coined for it.
The existing translation ' 末影铁 ' may have been used by other mods as a translation for 'end iron', and '末影铁' may associate this metal with teleportation such as enderman and ender pearl (in fact, it is only a common mineral). so I think we can consider '赛蓝铁' as the translation of thallasium.

**Comment by aoligei635** [comment]
> A new translation idea: When I looked up some previous Chinese translation documents, I found that 'thallasium' was translated as '赛蓝铁'. I think this is a translation that can be referenced. Firstly, because thallasium is a fictional substance, a word can be coined for it. The existing translation ' 末影铁 ' may have been used by other mods as a translation for 'end iron', and '末影铁' may associate this metal with teleportation such as enderman and ender pearl (in fact, it is only a common mineral). so I think we can consider '赛蓝铁' as the translation of thallasium.

Emm... good idea.But I need to think carefully.Maybe I will give you my judgement about it on Sunday this week.

**Comment by aoligei635** [comment]
> A new translation idea: When I looked up some previous Chinese translation documents, I found that 'thallasium' was translated as '赛蓝铁'. I think this is a translation that can be referenced. Firstly, because thallasium is a fictional substance, a word can be coined for it. The existing translation ' 末影铁 ' may have been used by other mods as a translation for 'end iron', and '末影铁' may associate this metal with teleportation such as enderman and ender pearl (in fact, it is only a common mineral). so I think we can consider '赛蓝铁' as the translation of thallasium.

I'm sorry that I reply you sooooooooooooooooooooooo lately,reasons for that are I usually forget to reply and I'm too busy when I started to go to school.

Actually, I don't think it's a good translation.Although ”末影铁“ has been shown in many mods,they just add a ore that can be smelted to the vanilla iron ingot.Why I translate thallasium to ”末影铁" because I think they can only find at The End and some functions are same as the iron ingot,enderman lives in The End,thallasium also exists in The End.why not thallasium can not be called “末影铁”?

**Comment by IwasConfused** [comment]
> > A new translation idea: When I looked up some previous Chinese translation documents, I found that 'thallasium' was translated as '赛蓝铁'. I think this is a translation that can be referenced. Firstly, because thallasium is a fictional substance, a word can be coined for it. The existing translation ' 末影铁 ' may have been used by other mods as a translation for 'end iron', and '末影铁' may associate this metal with teleportation such as enderman and ender pearl (in fact, it is only a common mineral). so I think we can consider '赛蓝铁' as the translation of thallasium.
> 
> I'm sorry that I reply you sooooooooooooooooooooooo lately,reasons for that are I usually forget to reply and I'm too busy when I started to go to school.
> 
> Actually, I don't think it's a good translation.Although ”末影铁“ has been shown in many mods,they just add a ore that can be smelted to the vanilla iron ingot.Why I translate thallasium to ”末影铁" because I think they can only find at The End and some functions are same as the iron ingot,enderman lives in The End,thallasium also exists in The End.why not thallasium can not be called “末影铁”?

Thank you for your reply!
Actually, I have had such considerations before, and I have prepared a compromise plan for this: '末地铁'
In the official translation of vanilla, "end" corresponds to "末地", like 'end crystal'; And 'ender' corresponds to '末影', like ' ender pearl '.
I think using the translation of '末地铁' can avoid the misunderstanding I mentioned earlier about the functionality of thallasium, and can also express the characteristics of thallasium related to the End that you mentioned.

**Comment by aoligei635** [comment]
> > > A new translation idea: When I looked up some previous Chinese translation documents, I found that 'thallasium' was translated as '赛蓝铁'. I think this is a translation that can be referenced. Firstly, because thallasium is a fictional substance, a word can be coined for it. The existing translation ' 末影铁 ' may have been used by other mods as a translation for 'end iron', and '末影铁' may associate this metal with teleportation such as enderman and ender pearl (in fact, it is only a common mineral). so I think we can consider '赛蓝铁' as the translation of thallasium.
> > 
> > 
> > I'm sorry that I reply you sooooooooooooooooooooooo lately,reasons for that are I usually forget to reply and I'm too busy when I started to go to school.
> > Actually, I don't think it's a good translation.Although ”末影铁“ has been shown in many mods,they just add a ore that can be smelted to the vanilla iron ingot.Why I translate thallasium to ”末影铁" because I think they can only find at The End and some functions are same as the iron ingot,enderman lives in The End,thallasium also exists in The End.why not thallasium can not be called “末影铁”?
> 
> Thank you for your reply! Actually, I have had such considerations before, and I have prepared a compromise plan for this: '末地铁' In the official translation of vanilla, "end" corresponds to "末地", like 'end crystal'; And 'ender' corresponds to '末影', like ' ender pearl '. I think using the translation of '末地铁' can avoid the misunderstanding I mentioned earlier about the functionality of thallasium, and can also express the characteristics of thallasium related to the End that you mentioned.

Ah.I'm sorry.I think I have a wrong memory.When I searched the "末地铁" on the MC BaiKe,one of the biggest MOD Wiki in China.I found that almost all of items named "end iron" were translated to "末地铁",and I only found one item was named "末影铁".The mod which has the end iron is only supporting MC 1.12.2 and this mod's author was no longer to update it.So maybe no mod has the end iron on newer versions than 1.12.2.

This is my fault.I'm sorry.

**Pull request merged**
