### PR TITLE
Lossless assets compression

### PR DESCRIPTION
**Pull request by Shazuli**
Losslessly compressing the assets a bit.

### CODE REVIEW

**Comment by Shazuli** [comment]
Final build jar went from 86.9 MB to 74.7 MB.

**Comment by quiqueck** [comment]
Thank you very much for your time :)

**Review by quiqueck — CHANGES_REQUESTED** [review]
I am currently reviewing the changes and noticed that src/main/resources/assets/betterend/sounds/ambient/caves.ogg appears to be a faulty compression. At least for me the sound is quite corrupted...

I have not yet reviewed all other sound files, so I am not sure if this is an isolated matter.

**Comment by quiqueck** [comment]
dust_wastelands.off appears to be broken too...

**Comment by Shazuli** [comment]
Huh. Didn't notice that, strange. I did the same process with all of them so not sure why those got messed up. Will listen through them all and see if any other files got messed up.

**Comment by quiqueck** [comment]
Thank you very much :)

**Comment by Shazuli** [comment]
There were a few files that got messed up. I can't get the project I used to compress the files compiled on this PC (don't have access to my main one) for whatever reason so I will have to wait until I get back home. Will sort out those files then.

**Comment by Shazuli** [comment]
Ok, finally got the files sorted out @quiqueck.
Compressed the files that made a difference in file size (some got slightly bigger after compression so skipped those).
Listened to all the audio files this time and it sounds like nothing got messed up this time. I don't have any tools to compare audio file quality, but in my opinion they sound exactly the same as before compression.

**Comment by Shazuli** [comment]
Just a reminder that it's ready to be merged @quiqueck.

**Comment by quiqueck** [comment]
Thanks for the reminder :)

**Review by quiqueck — APPROVED** [review]

**Comment by purejosh** [comment]
What was the final space gains had with this method?

**Comment by quiqueck** [comment]
You can see the file changes on the [Files changed](https://github.com/quiqueck/BetterEnd/pull/2/files) tab at the tob

**Comment by purejosh** [comment]
I do want to urge caution against compressing images with such a small space gain. Images can compress, and while they won't show fidelity issues immediately, any additional compressions to them afterwards can cause artifacts and noise in the image, especially colorful ones. I'm not sure a couple of kilobytes is worth it, but that's just my opinion. 🙂

**Comment by quiqueck** [comment]
I am currently reviewing those changes. As they are png-files, there is usually no loss in fidelity.

**Pull request merged**
