### PR TITLE
Fix endCityFailChance config. Fix slime variant.

### PR DESCRIPTION
**Pull request by Necrontyrr**
In addition to adding the missing mixin, I also sorted the array alphabetically because yes.

### CODE REVIEW

**Comment by Necrontyrr** [comment]
I added a new unrelated commit by mistake instead of creating a new PR, sorry. I changed the PR title to reflect that.

**Comment by Necrontyrr** [comment]
I am no mathematician or algorithm expert so I don't know how internally the xoroshift pseudorandom number generator works. What I found was only based on testing numbers by hand.
When the chunkpos is low, the result of the random generator is always 0. Calling consumeCount() solved that.
However, I just noticed that when the chance has a value less than 5, it always returns a constant value that doesn't change for thousands or millions of chunks, depending on the value. The consumeCount fix above doesn't solve this.
The only way I found was to multiply a very high/low number (the seed for example) by the chunkpos, even if it overflows Long.MAX_VALUE/MIN_VALUE.

Values 0/1 = normal generation chance. Values of 2+ have a chance of 1/value. Maybe should change the default config value too.

**Comment by Necrontyrr** [comment]
Please forgive my ineptutude. I am still learning the Minecraft API and I didn't know that `Structure.GenerationContext` already provides a random generator, that works just fine.

**Comment by quiqueck** [comment]
Great fixes, thank you very much! I will test those on the weekend.

**Pull request merged**
